spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: board
    password: boardpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET:farmsystemprestudy}
  access-ttl-seconds: ${JWT_ACCESS_TTL:1800}
  refresh-ttl-seconds: ${JWT_REFRESH_TTL:1209600}

logging:
  level:
    org.hibernate.SQL: debug
